sudo: required
services:
    - docker

before_install:
    - docker build -t rachitagrawal/docker-react-frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true rachitagrawal/docker-react-frontend npm run test
 
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react-frontend"
    env: "DockerReactFrontend-env"
    bucket_name: "elasticbeanstalk-us-west-2-511344908378"
    bucket_path: "docker-react-frontend"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY